model_dir: catkin_ws/src/push_planners/twc-stable-push-net-ros/models

# Inference Configuration
planner:
  gripper: "hanyang"  # "vertical", "hanyang"
  # num_push_directions: 8
  num_push_directions: 12
  gripper_width: 0.055

  # visualize: True
  visualize: False
  image_type: "masked_image"

depth_based:
  friction_coefficient: 1

network:
  # model_name: "2024-05-20-vertical"
  model_name: "2024-06-17-hanyang"

hybrid:
  grid_size: 0.05  # unit: m
  dtheta:  5  # unit: deg

gripper:
  vertical:
    height: 0.03
    z_angle: 0
    finger_angle: 180 # robotiq2f
    x_offset: 0


  hanyang:
    height: 0.015
    # height: 0.03
    # z_angle: -1.81759703
    z_angle: +13.1825
    finger_angle: 120 # hanyang
    x_offset: -0.038990381

