model_dir: catkin_ws/src/push_planners/twc-stable-push-net-ros/models

# Inference Configuration
planner:
  gripper: "vertical"
  # gripper: "hanyang"
  gripper_width: 0.075
  height: 0.03
  num_push_directions: 6
  # num_push_directions: 8

  # visualize: True
  visualize: False
  image_type: "masked_image"

depth_based:
  friction_coefficient: 1

network:
  # model_name: "2024-05-20-0000"
  model_name: "2024-06-17-1334"

hybrid:
  grid_size: 0.05  # unit: m
  dtheta:  5  # unit: deg

# Train Configuration
file_zero_padding_num: 7

gripper:
  vertical:
    height: 0.03
    z_angle: 0
    finger_angle: 180 # robotiq2f
    x_offset: 0


  hanyang:
    height: 0.015
    z_angle: 0
    finger_angle: 120 # hanyang
    x_offset: -0.038990381

